-- 관리자 계정 생성용 
UPDATE DELIVERY_MEMBER
SET ROLENAME = 'ROLE_ADMIN'
WHERE MEMBERID = '';

-- 메세지 신고 테이블
CREATE TABLE MESSAGEREPORT(
    REPORTNUM NUMBER PRIMARY KEY,
    SENDER VARCHAR2(30),
	MESSAGE VARCHAR2(4000),
	REPORTER VARCHAR2(4000),
	ROOMID VARCHAR2(500) REFERENCES CHATROOM(ROOMID),
	INPUTDATE DATE DEFAULT SYSDATE
);
-- 메세지 신고 시퀀스
CREATE SEQUENCE MESSAGEREPORT_SEQ;

-- 밴 당한 사람 테이블
CREATE TABLE BANLIST (
    MEMBERID VARCHAR2(30), -- 가해자
    MESSAGE VARCHAR2(4000), -- 사유
    REPORTER VARCHAR2(30), -- 신고자
    INPUTDATE DATE DEFAULT SYSDATE -- 정지일
);
-- 채팅방 테이블
CREATE TABLE CHATROOM(
    ROOMID VARCHAR2(500) PRIMARY KEY,
    ROOMNAME VARCHAR2(100),
    INPUTDATE DATE DEFAULT SYSDATE
);

-- 회원 테이블
CREATE TABLE DELIVERY_MEMBER(
    MEMBERNUM NUMBER PRIMARY KEY,
    MEMBERID VARCHAR2(100) UNIQUE,
    MEMBERPW VARCHAR2(1000) NOT NULL,
    MEMBERNAME VARCHAR2(30) NOT NULL,
    NICKNAME VARCHAR2(30) NOT NULL,
    PINNUMBER VARCHAR2(30),
    ADDRESS VARCHAR2(1000), 
    PHONE VARCHAR2(30),
    MEMBEREXP NUMBER DEFAULT 0,
    MEMBERPOINT NUMBER DEFAULT 0,
    ROOMID VARCHAR2(500),  
    MEMBERLEVEL NUMBER DEFAULT 1,
    
    ENABLED NUMBER(1) DEFAULT 1 CHECK(ENABLED = 0 OR ENABLED = 1),
    ROLENAME VARCHAR2(10) DEFAULT 'ROLE_USER' CHECK(ROLENAME = 'ROLE_ADMIN' OR ROLENAME = 'ROLE_USER'),
    
    ORIGINALFILE VARCHAR2(200),
    SAVEDFILE VARCHAR2(200)
);

-- 회원번호 시퀀스
CREATE SEQUENCE DELIVERY_MEMBER_SEQ;

-- 가게등록 테이블
CREATE TABLE STORE(
    STORENUM NUMBER PRIMARY KEY,
    MEMBERNUM NUMBER REFERENCES DELIVERY_MEMBER(MEMBERNUM) ON DELETE CASCADE NOT NULL,
    STORENAME VARCHAR2(30) NOT NULL,
    STORECONTENT VARCHAR2(1000),
    CATEGORY VARCHAR2(30) NOT NULL,
    ADDRESS VARCHAR2(1000) NOT NULL,
    PHONE VARCHAR2(30) NOT NULL,
    RATING NUMBER DEFAULT 0,
    WISHLIST NUMBER DEFAULT 0,
    
    ORIGINALFILE VARCHAR2(200),
    SAVEDFILE VARCHAR2(200)  
);

-- 가게번호 시퀀스
CREATE SEQUENCE STORE_SEQ;

-- 상품등록 테이블
CREATE TABLE ITEM_TABLE(
    ITEMNUM NUMBER PRIMARY KEY,
    STORENUM NUMBER REFERENCES STORE(STORENUM) ON DELETE CASCADE NOT NULL,
    ITEMNAME VARCHAR2(30) NOT NULL,
    ITEMCONTENT VARCHAR2(1000) NOT NULL,
    ITEMPRICE NUMBER NOT NULL,
    
    ORIGINALFILE VARCHAR2(200),
    SAVEDFILE VARCHAR2(200)
);

-- 상품번호 시퀀스
CREATE SEQUENCE ITEM_SEQ;

-- 주문등록 테이블
CREATE TABLE ORDER_TABLE(
    ORDERNUM NUMBER PRIMARY KEY,
    MEMBERNUM NUMBER REFERENCES DELIVERY_MEMBER(MEMBERNUM) ON DELETE CASCADE NOT NULL,
    ITEMNUM NUMBER REFERENCES ITEM_TABLE(ITEMNUM) ON DELETE CASCADE NOT NULL,
    STORENUM NUMBER REFERENCES STORE(STORENUM) ON DELETE CASCADE NOT NULL,
    ITEMNAME VARCHAR2(30) NOT NULL,
    ITEMPRICE NUMBER NOT NULL,
    QUANTITY NUMBER DEFAULT 1,
    COMPLETE CHAR DEFAULT 'N' CHECK(COMPLETE = 'N' OR COMPLETE = 'Y')
);
-- 주문 번호 시퀀스
CREATE SEQUENCE ORDER_SEQ;
-- 영수증 테이블
CREATE TABLE RECEIPT(
    RECEIPTNUM NUMBER PRIMARY KEY,
    MEMBERNUM NUMBER REFERENCES DELIVERY_MEMBER(MEMBERNUM) ON DELETE CASCADE NOT NULL,
    STORENUM NUMBER REFERENCES STORE(STORENUM) ON DELETE CASCADE NOT NULL,
    ORDERHISTORY VARCHAR2(1000) NOT NULL,
    TOTALAMOUNT NUMBER NOT NULL,
    ORDERADDRESS VARCHAR2(1000),
    WAITING CHAR DEFAULT 'N' CHECK(WAITING = 'N' OR WAITING = 'Y'),
    COMPLETE CHAR DEFAULT 'N' CHECK(COMPLETE = 'N' OR COMPLETE = 'Y')
);

-- 영수증 시퀀스
CREATE SEQUENCE RECEIPT_SEQ;

-- 리뷰 테이블
CREATE TABLE REVIEW(
    REVIEWNUM NUMBER PRIMARY KEY,
    MEMBERNUM NUMBER REFERENCES DELIVERY_MEMBER(MEMBERNUM) ON DELETE CASCADE NOT NULL,
    STORENUM NUMBER REFERENCES STORE(STORENUM) ON DELETE CASCADE NOT NULL,
    RECEIPTNUM NUMBER REFERENCES RECEIPT(RECEIPTNUM) ON DELETE CASCADE NOT NULL,
    NICKNAME VARCHAR2(30) NOT NULL,
    ORDERHISTORY VARCHAR2(1000) NOT NULL,
    RATING NUMBER DEFAULT 5 NOT NULL,
    COMPLETE CHAR DEFAULT 'N' CHECK(COMPLETE = 'N' OR COMPLETE = 'Y'),
    REVIEWCONTENT VARCHAR2(500) NOT NULL
);

-- 리뷰 번호 시퀀스
CREATE SEQUENCE REVIEW_SEQ;

-- 찜 테이블
CREATE TABLE WISHLIST(
    MEMBERNUM NUMBER REFERENCES DELIVERY_MEMBER(MEMBERNUM) ON DELETE CASCADE NOT NULL,
    MEMBERID VARCHAR2(30),
    STORENUM NUMBER REFERENCES STORE(STORENUM) ON DELETE CASCADE NOT NULL
);

-- 경험치 테이블
CREATE TABLE EXP_TABLE(
    USERLEVEL NUMBER unique,
    USEREXP NUMBER NOT NULL
);

-- 상품권 등록 테이블
CREATE TABLE COUPON(
    COUPONNUM NUMBER PRIMARY KEY,
    COUPONNAME VARCHAR2(30) NOT NULL,
    COUPONPOINT NUMBER NOT NULL
);

-- 상품권 번호 시퀀스
CREATE SEQUENCE COUPON_SEQ;

-- 소지 상품권 테이블
CREATE TABLE MYCOUPON(
    MYCOUPONNUM NUMBER PRIMARY KEY,
    MEMBERNUM NUMBER REFERENCES DELIVERY_MEMBER(MEMBERNUM) ON DELETE CASCADE NOT NULL,
    COUPONNUM NUMBER REFERENCES COUPON(COUPONNUM) ON DELETE CASCADE NOT NULL,
    COUPONNAME VARCHAR2(30) NOT NULL,
    COUPONPOINT NUMBER NOT NULL
);

-- 소지 쿠폰 번호 시퀀스
CREATE SEQUENCE MYCOUPON_SEQ;

-- 자유게시판 
CREATE TABLE FREE_BOARD(
    BOARDNUM NUMBER PRIMARY KEY,
    MEMBERNUM NUMBER REFERENCES DELIVERY_MEMBER(MEMBERNUM) ON DELETE CASCADE NOT NULL,
    NICKNAME VARCHAR2(30) NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    INPUTDATE DATE DEFAULT SYSDATE,
    VIEWCOUNT NUMBER DEFAULT 0,
    MEMBERLEVEL NUMBER DEFAULT 1,
    
    ORIGINALFILE VARCHAR2(200),
    SAVEDFILE VARCHAR2(200)
);


-- 자유게시글 번호
CREATE SEQUENCE BOARDNUM_SEQ;

-- 자유게시판 댓글 
CREATE TABLE FREE_REPLY(
    REPLYNUM NUMBER PRIMARY KEY,
    BOARDNUM NUMBER REFERENCES FREE_BOARD(BOARDNUM) ON DELETE CASCADE NOT NULL,
    MEMBERNUM NUMBER REFERENCES DELIVERY_MEMBER(MEMBERNUM) ON DELETE CASCADE NOT NULL,
    NICKNAME VARCHAR2(30) NOT NULL,
    CONTENT VARCHAR2(500) NOT NULL,
    INPUTDATE DATE DEFAULT SYSDATE,
    MEMBERLEVEL NUMBER DEFAULT 1
);

-- 댓글 시퀀스
CREATE SEQUENCE FREE_REPLY_SEQ;

-- 모집 게시판
CREATE TABLE CLASS_BOARD(
    CLASSNUM NUMBER PRIMARY KEY,
    MEMBERNUM NUMBER REFERENCES DELIVERY_MEMBER(MEMBERNUM) ON DELETE CASCADE NOT NULL,
    DESTINATION VARCHAR2(1000) NOT NULL,    -- 목적지
    TOTALMEMBER NUMBER DEFAULT 2 NOT NULL,
    NICKNAME VARCHAR2(30) NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL,
    INPUTDATE DATE DEFAULT SYSDATE,
    CLASSTAG VARCHAR2(2000),
    ROOMID VARCHAR2(500) REFERENCES CHATROOM(ROOMID) ON DELETE CASCADE NOT NULL, 
    MEMBERLEVEL NUMBER DEFAULT 1,
    VIEWCOUNT    NUMBER DEFAULT 0,
    
    ORIGINALFILE VARCHAR2(200),
    SAVEDFILE VARCHAR2(200)
);

-- 모집 게시글번호 시퀀스
CREATE SEQUENCE CLASS_BOARD_SEQ;

-- 모임방
CREATE TABLE CLASS_ROOM(
    ROOMNUM NUMBER PRIMARY KEY,
    CLASSNUM NUMBER REFERENCES CLASS_BOARD(CLASSNUM) ON DELETE CASCADE NOT NULL,
    MEMBERNUM NUMBER REFERENCES DELIVERY_MEMBER(MEMBERNUM) ON DELETE CASCADE NOT NULL,
    NICKNAME VARCHAR2(30) NOT NULL,
    MEMBERLEVEL NUMBER DEFAULT 1,
    ADDRESS VARCHAR2(1000) NOT NULL,
    
    ORIGINALFILE VARCHAR2(200),
    SAVEDFILE VARCHAR2(200)
);

-- 모임방 시퀀스
CREATE SEQUENCE CLASS_ROOM_SEQ;

-- 방명록
CREATE TABLE GUESTBOOK(
    GUESTBOOKNUM NUMBER PRIMARY KEY,
    MEMBERNUM NUMBER REFERENCES DELIVERY_MEMBER(MEMBERNUM) ON DELETE CASCADE NOT NULL,
    WRITERNUM NUMBER,
    NICKNAME VARCHAR2(30) NOT NULL,
    CONTENT VARCHAR2(500) NOT NULL,
    INPUTDATE DATE DEFAULT SYSDATE   
);

-- 방명록 시퀀스
CREATE SEQUENCE GUESTBOOK_SEQ;

CREATE TABLE MULTI_FILE_TABLE_OF_FREE_BOARD(
    FILENUM NUMBER PRIMARY KEY,
    BOARDNUM NUMBER REFERENCES FREE_BOARD(BOARDNUM),
    ORIGINALFILE VARCHAR2(200),
    SAVEDFILE VARCHAR2(200),
    FILESIZE NUMBER NOT NULL,
    DELETE_YN VARCHAR2(5) DEFAULT 'N' CHECK(DELETE_YN = 'Y' OR DELETE_YN = 'N') NOT NULL,
    INSERT_TIME DATE DEFAULT SYSDATE,
    DELETE_TIME DATE NULL
    );
-- 멀티파일 시퀀스
CREATE SEQUENCE FILE_TABLE_SEQ_OF_FREE_BOARD;
